# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: ""

### Header
header:
  logo:
    image: "assets/img/logo2.png"
    alt: ""

### Footer
footer:
  developer: "Developed by <strong>bslthemes</strong>"
  copyright: "<strong>Luique</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "암호화"
      slug: "암호화"

    - name: "Photography"
      slug: "photography"

    - name: "Development"
      slug: "development"

    - name: "Branding"
      slug: "branding"
