# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo2.png"
    alt: ""

### Header
header:
  logo:
    image: "assets/img/logo2.png"
    alt: ""

### Footer
footer:
  developer: "Developed by <strong>bslthemes</strong>"
  copyright: "<strong>Luique</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "PROJECT"
      slug: "PROJECT"

    - name: "Linux"
      slug: "Linux 실습"

    # - name: "SNORT"
    #   slug: "Snort 실습"

    - #name: "Branding"
      #slug: "branding"
